# Form implementation generated from reading ui file 'main_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_2(object):
    def setupUi(self, Main_2):
        Main_2.setObjectName("Main_2")
        Main_2.resize(221, 233)
        self.centralwidget = QtWidgets.QWidget(Main_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.play_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.play_button_2.setGeometry(QtCore.QRect(50, 130, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.play_button_2.setFont(font)
        self.play_button_2.setObjectName("play_button_2")
        Main_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_2)
        QtCore.QMetaObject.connectSlotsByName(Main_2)

    def retranslateUi(self, Main_2):
        _translate = QtCore.QCoreApplication.translate
        Main_2.setWindowTitle(_translate("Main_2", "MainWindow"))
        self.label.setText(_translate("Main_2", "Gamer 2"))
        self.play_button_2.setText(_translate("Main_2", "Play"))
