# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_1(object):
    def setupUi(self, Main_1):
        Main_1.setObjectName("Main_1")
        Main_1.resize(221, 233)
        self.centralwidget = QtWidgets.QWidget(Main_1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.play_button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.play_button_1.setGeometry(QtCore.QRect(50, 130, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.play_button_1.setFont(font)
        self.play_button_1.setObjectName("play_button_1")
        Main_1.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_1)
        QtCore.QMetaObject.connectSlotsByName(Main_1)

    def retranslateUi(self, Main_1):
        _translate = QtCore.QCoreApplication.translate
        Main_1.setWindowTitle(_translate("Main_1", "MainWindow"))
        self.label.setText(_translate("Main_1", "Gamer 1"))
        self.play_button_1.setText(_translate("Main_1", "Play"))
